name: Bug Report
description: File a bug report
labels: ["Bug", "Servers"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: steamid
    attributes:
      label: Steam ID or Profile
      description: We will reward you with the bounty if this is resolved.
      placeholder: e.g. https://steamcommunity.com/profiles/76561198088419275
    validations:
      required: true
  - type: input
    id: server
    attributes:
      label: Server IP
      description: What server did this occur on? Paste the IP address here.
      placeholder: 209.58.160.137:27000
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What Happened?
      description: Also tell us, how to reproduce the bug and what did you expect to happen? If you have any screenshots that may help us better understand the problem, please include them.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: No Critical Security Exploits
      description: By submitting this issue, you agree that this report does not contain any specific details on a critical security exploit.
      options:
        - label: I agree
          required: true
- type: checkboxes
    id: rules
    attributes:
      label: Rules of Conduct
      description: By submitting this issue, you agree that you will not abuse this bug to your advantage.
      options:
        - label: I agree
          required: true
